apiVersion: v1
kind: ConfigMap
metadata:
  name: primehealth-config
data:
  NODE_ENV: production
  AUTH_PORT: "5001"
  PATIENT_PORT: "5001"
  APPOINTMENT_PORT: "5003"
  PAYMENT_PORT: "5004"
  TELEMEDICINE_PORT: "5006"
  PATIENT_SERVICE_URL: "http://patient-service:5001"
  ADMIN_SERVICE_URL: "http://auth-service:5001"
  DOCTOR_SERVICE_URL: "http://doctor-service:5002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5003"
  PRESCRIPTION_SERVICE_URL: "http://prescription-service:5005"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:5006"
  INVOICE_DIR: "./invoices"
  INTERNAL_SERVICE_TOKEN: "primehealth-internal-sync-token"
  JWT_EXPIRES_IN: "7d"
  JITSI_BASE_URL: "https://meet.jit.si"
  VIDEO_PROVIDER: "jitsi"
  MONGODB_URI_APPOINTMENT: "mongodb://mongodb:27017/appointments"
  MONGODB_URI_PAYMENT: "mongodb://mongodb:27017/payments"
  MONGODB_URI_DOCTOR: "mongodb://mongodb:27017/doctors"
  MONGODB_URI_PATIENT: "mongodb://mongodb:27017/patients"
  MONGODB_URI_ADMIN: "mongodb://mongodb:27017/admin"
  MONGODB_URI_TELEMEDICINE: "mongodb://mongodb:27017/telemedicine"
