# version: '3.8'

services:
  api-gateway:
    build: ../services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - patient-service

  auth-service:
    build: ../services/auth-service
    ports:
      - "3001:3001"

  patient-service:
    build: ../services/patient-service
    ports:
      - "3002:3002"

  appointment-service:
    build: ../services/appointment-service
    ports:
      - "3003:3003"

  notification-service:
    build: ../services/notification-service
    ports:
      - "3004:3004"
